trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: dotnet build
  displayName: 'Build the project'

- script: docker build -t demodevops:$(Build.BuildId) .
  displayName: 'Build Docker image'
