trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildStage
  displayName: 'Compilación'
  jobs:
  - job: Build
    displayName: 'Build Project'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build projects'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration Release --no-restore'

- stage: TestStage
  displayName: 'Pruebas Unitarias'
  dependsOn: BuildStage
  condition: succeeded()
  jobs:
  - job: Test
    displayName: 'Unit Tests'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests'
      inputs:
        command: 'test'
        projects: 'DemoDevOps.Tests/DemoDevOps.Tests.csproj'
        arguments: '--configuration Release --logger trx'
        publishTestResults: true

- stage: Packaging
  displayName: 'Empaquetado'
  dependsOn: TestStage
  condition: succeeded()
  jobs:
  - job: DockerBuild
    displayName: 'Build Docker Image'
    steps:
    - script: docker build -t demodevops:$(Build.BuildId) .
      displayName: 'Build Docker image'
