services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "${DB_PASSWORD}"
      MSSQL_PID: "Developer"
    volumes:
      - sqlserverdata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demodevops_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ConexionSql=Server=sql;Database=DemoDevOpsDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=true;
    depends_on:
      - sql

volumes:
  sqlserverdata:
